In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Rosstat/data-2018.csv', sep=';', names=[x for x in range(0, 266)], encoding='cp1251')

In [102]:
# df_new = df[df[df.columns[4]] == '51.51'] # if < 2016
df_new = df[df[df.columns[4]] == '46.71'] # if >= 2016
df_new.columns = np.arange(len(df.columns))
cols = [x for x in range(8, 265)]
df_new.head()
df_384 = df_new[(df_new[df_new.columns[6]] == 384)]
df_384[cols] = df_384[cols].apply(lambda x: x * 1000)
df_385 = df_new[(df_new[df_new.columns[6]] == 385)]
df_385[cols] = df_385[cols].apply(lambda x: x * 1000000)
final = pd.concat([df_384, df_385], ignore_index=True)

In [103]:
final

,0,1,2,3,4,5,6,7,8,9,...,256,257,258,259,260,261,262,263,264,265
0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АСК""",48449,12300,16,46.71,2221225768,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190722
1,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АОРТА""",531068,12300,16,46.71,2222857953,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190722
2,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ОСНОВА""",531217,12300,16,46.71,2249012576,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190722
3,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ТК ""С...",576415,12300,16,46.71,2222845595,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190722
4,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ФАВО...",636471,65,16,46.71,2312240876,384,2,0,0,...,0,0,0,0,0,0,0,0,0,20190402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13076,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""УСПЕХ""",2552985,12300,16,46.71,2721224138,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190521
13077,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЕВРО...",20290201,12300,16,46.71,7901549127,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190313
13078,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЕВРО...",38689984,12300,16,46.71,7901546510,384,1,0,0,...,0,0,0,0,0,0,0,0,0,20190313
13079,"Общество с ограниченной ответственностью ""БирУ...",89447018,12300,16,46.71,7901537837,384,2,0,0,...,0,0,0,0,0,0,0,0,0,20190129
13080,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ХАБА...",32187661,12300,16,46.71,2721220817,385,2,0,0,...,0,0,0,0,0,0,0,0,0,20190624

In [104]:
final.to_csv('rosstat_2018.csv', index=False)